// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClickLogsByLink = `-- name: CountClickLogsByLink :one
SELECT COUNT(*) AS total
FROM click_logs
WHERE link_id = $1
`

func (q *Queries) CountClickLogsByLink(ctx context.Context, linkID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClickLogsByLink, linkID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getClickLogsByLink = `-- name: GetClickLogsByLink :many
SELECT id, link_id, ip_address, referer, country, user_agent, clicked_at
FROM click_logs
WHERE link_id = $1
ORDER BY clicked_at DESC
LIMIT $2 OFFSET $3
`

type GetClickLogsByLinkParams struct {
	LinkID int64 `json:"link_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetClickLogsByLink(ctx context.Context, arg GetClickLogsByLinkParams) ([]ClickLog, error) {
	rows, err := q.db.Query(ctx, getClickLogsByLink, arg.LinkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClickLog
	for rows.Next() {
		var i ClickLog
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.IpAddress,
			&i.Referer,
			&i.Country,
			&i.UserAgent,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStatsByLink = `-- name: GetDailyStatsByLink :many
SELECT link_id, date, clicks, unique_visitors, countries, referers
FROM daily_stats
WHERE link_id = $1
    AND date >= $2
    AND date <= $3
ORDER BY date DESC
`

type GetDailyStatsByLinkParams struct {
	LinkID int64       `json:"link_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDailyStatsByLink(ctx context.Context, arg GetDailyStatsByLinkParams) ([]DailyStat, error) {
	rows, err := q.db.Query(ctx, getDailyStatsByLink, arg.LinkID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyStat
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.LinkID,
			&i.Date,
			&i.Clicks,
			&i.UniqueVisitors,
			&i.Countries,
			&i.Referers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkStatsSummary = `-- name: GetLinkStatsSummary :one
SELECT
    COALESCE(SUM(clicks), 0)::bigint AS total_clicks,
    COALESCE(SUM(unique_visitors), 0)::bigint AS total_unique_visitors
FROM daily_stats
WHERE link_id = $1
`

type GetLinkStatsSummaryRow struct {
	TotalClicks         int64 `json:"total_clicks"`
	TotalUniqueVisitors int64 `json:"total_unique_visitors"`
}

func (q *Queries) GetLinkStatsSummary(ctx context.Context, linkID int64) (GetLinkStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLinkStatsSummary, linkID)
	var i GetLinkStatsSummaryRow
	err := row.Scan(&i.TotalClicks, &i.TotalUniqueVisitors)
	return i, err
}

const insertClickLog = `-- name: InsertClickLog :one
INSERT INTO click_logs (link_id, ip_address, referer, country, user_agent, clicked_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, link_id, ip_address, referer, country, user_agent, clicked_at
`

type InsertClickLogParams struct {
	LinkID    int64              `json:"link_id"`
	IpAddress *netip.Addr        `json:"ip_address"`
	Referer   pgtype.Text        `json:"referer"`
	Country   pgtype.Text        `json:"country"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ClickedAt pgtype.Timestamptz `json:"clicked_at"`
}

func (q *Queries) InsertClickLog(ctx context.Context, arg InsertClickLogParams) (ClickLog, error) {
	row := q.db.QueryRow(ctx, insertClickLog,
		arg.LinkID,
		arg.IpAddress,
		arg.Referer,
		arg.Country,
		arg.UserAgent,
		arg.ClickedAt,
	)
	var i ClickLog
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.IpAddress,
		&i.Referer,
		&i.Country,
		&i.UserAgent,
		&i.ClickedAt,
	)
	return i, err
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(
    SELECT 1 FROM processed_events WHERE task_id = $1
) AS processed
`

func (q *Queries) IsEventProcessed(ctx context.Context, taskID string) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, taskID)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO processed_events (task_id, job_type)
VALUES ($1, $2)
`

type MarkEventProcessedParams struct {
	TaskID  string `json:"task_id"`
	JobType string `json:"job_type"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.TaskID, arg.JobType)
	return err
}

const upsertDailyStats = `-- name: UpsertDailyStats :exec
INSERT INTO daily_stats (link_id, date, clicks, unique_visitors, countries, referers)
SELECT
    cl.link_id,
    cl.clicked_at::date AS date,
    COUNT(*) AS clicks,
    COUNT(DISTINCT md5(COALESCE(cl.ip_address::text, '') || COALESCE(cl.user_agent, ''))) AS unique_visitors,
    COALESCE(jsonb_object_agg(cl.country, cl.country_cnt) FILTER (WHERE cl.country IS NOT NULL), '{}') AS countries,
    COALESCE(jsonb_object_agg(cl.referer, cl.referer_cnt) FILTER (WHERE cl.referer IS NOT NULL), '{}') AS referers
FROM (
    SELECT
        link_id,
        clicked_at,
        ip_address,
        user_agent,
        country,
        referer,
        COUNT(*) OVER (PARTITION BY link_id, clicked_at::date, country) AS country_cnt,
        COUNT(*) OVER (PARTITION BY link_id, clicked_at::date, referer) AS referer_cnt
    FROM click_logs
    WHERE clicked_at >= $1
      AND clicked_at < $2
) cl
GROUP BY cl.link_id, cl.clicked_at::date
ON CONFLICT (link_id, date)
DO UPDATE SET
    clicks = EXCLUDED.clicks,
    unique_visitors = EXCLUDED.unique_visitors,
    countries = EXCLUDED.countries,
    referers = EXCLUDED.referers
`

type UpsertDailyStatsParams struct {
	ClickedAt   pgtype.Timestamptz `json:"clicked_at"`
	ClickedAt_2 pgtype.Timestamptz `json:"clicked_at_2"`
}

func (q *Queries) UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) error {
	_, err := q.db.Exec(ctx, upsertDailyStats, arg.ClickedAt, arg.ClickedAt_2)
	return err
}
