// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClickLogsByLink = `-- name: CountClickLogsByLink :one
SELECT COUNT(*) AS total
FROM click_logs
WHERE link_id = $1
`

func (q *Queries) CountClickLogsByLink(ctx context.Context, linkID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClickLogsByLink, linkID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getClickLogsByLink = `-- name: GetClickLogsByLink :many
SELECT id, link_id, ip_address, referer, country, user_agent, clicked_at
FROM click_logs
WHERE link_id = $1
ORDER BY clicked_at DESC
LIMIT $2 OFFSET $3
`

type GetClickLogsByLinkParams struct {
	LinkID int64 `json:"link_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetClickLogsByLink(ctx context.Context, arg GetClickLogsByLinkParams) ([]ClickLog, error) {
	rows, err := q.db.Query(ctx, getClickLogsByLink, arg.LinkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClickLog
	for rows.Next() {
		var i ClickLog
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.IpAddress,
			&i.Referer,
			&i.Country,
			&i.UserAgent,
			&i.ClickedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountryStats = `-- name: GetCountryStats :many
SELECT link_id, clicked_at::date AS date, country, COUNT(*) AS cnt
FROM click_logs
WHERE clicked_at >= $1 AND clicked_at < $2
    AND country IS NOT NULL
GROUP BY link_id, clicked_at::date, country
`

type GetCountryStatsParams struct {
	ClickedAt   pgtype.Timestamptz `json:"clicked_at"`
	ClickedAt_2 pgtype.Timestamptz `json:"clicked_at_2"`
}

type GetCountryStatsRow struct {
	LinkID  int64       `json:"link_id"`
	Date    pgtype.Date `json:"date"`
	Country pgtype.Text `json:"country"`
	Cnt     int64       `json:"cnt"`
}

func (q *Queries) GetCountryStats(ctx context.Context, arg GetCountryStatsParams) ([]GetCountryStatsRow, error) {
	rows, err := q.db.Query(ctx, getCountryStats, arg.ClickedAt, arg.ClickedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountryStatsRow
	for rows.Next() {
		var i GetCountryStatsRow
		if err := rows.Scan(
			&i.LinkID,
			&i.Date,
			&i.Country,
			&i.Cnt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStatsByLink = `-- name: GetDailyStatsByLink :many
SELECT link_id, date, clicks, unique_visitors, countries, referers
FROM daily_stats
WHERE link_id = $1
    AND date >= $2
    AND date <= $3
ORDER BY date DESC
`

type GetDailyStatsByLinkParams struct {
	LinkID int64       `json:"link_id"`
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetDailyStatsByLink(ctx context.Context, arg GetDailyStatsByLinkParams) ([]DailyStat, error) {
	rows, err := q.db.Query(ctx, getDailyStatsByLink, arg.LinkID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyStat
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.LinkID,
			&i.Date,
			&i.Clicks,
			&i.UniqueVisitors,
			&i.Countries,
			&i.Referers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkStatsSummary = `-- name: GetLinkStatsSummary :one
SELECT
    COALESCE(SUM(clicks), 0)::bigint AS total_clicks,
    COALESCE(SUM(unique_visitors), 0)::bigint AS total_unique_visitors
FROM daily_stats
WHERE link_id = $1
`

type GetLinkStatsSummaryRow struct {
	TotalClicks         int64 `json:"total_clicks"`
	TotalUniqueVisitors int64 `json:"total_unique_visitors"`
}

func (q *Queries) GetLinkStatsSummary(ctx context.Context, linkID int64) (GetLinkStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLinkStatsSummary, linkID)
	var i GetLinkStatsSummaryRow
	err := row.Scan(&i.TotalClicks, &i.TotalUniqueVisitors)
	return i, err
}

const getRefererStats = `-- name: GetRefererStats :many
SELECT link_id, clicked_at::date AS date, referer, COUNT(*) AS cnt
FROM click_logs
WHERE clicked_at >= $1 AND clicked_at < $2
    AND referer IS NOT NULL
GROUP BY link_id, clicked_at::date, referer
`

type GetRefererStatsParams struct {
	ClickedAt   pgtype.Timestamptz `json:"clicked_at"`
	ClickedAt_2 pgtype.Timestamptz `json:"clicked_at_2"`
}

type GetRefererStatsRow struct {
	LinkID  int64       `json:"link_id"`
	Date    pgtype.Date `json:"date"`
	Referer pgtype.Text `json:"referer"`
	Cnt     int64       `json:"cnt"`
}

func (q *Queries) GetRefererStats(ctx context.Context, arg GetRefererStatsParams) ([]GetRefererStatsRow, error) {
	rows, err := q.db.Query(ctx, getRefererStats, arg.ClickedAt, arg.ClickedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefererStatsRow
	for rows.Next() {
		var i GetRefererStatsRow
		if err := rows.Scan(
			&i.LinkID,
			&i.Date,
			&i.Referer,
			&i.Cnt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClickLog = `-- name: InsertClickLog :one
INSERT INTO click_logs (link_id, ip_address, referer, country, user_agent, clicked_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, link_id, ip_address, referer, country, user_agent, clicked_at
`

type InsertClickLogParams struct {
	LinkID    int64              `json:"link_id"`
	IpAddress *netip.Addr        `json:"ip_address"`
	Referer   pgtype.Text        `json:"referer"`
	Country   pgtype.Text        `json:"country"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ClickedAt pgtype.Timestamptz `json:"clicked_at"`
}

func (q *Queries) InsertClickLog(ctx context.Context, arg InsertClickLogParams) (ClickLog, error) {
	row := q.db.QueryRow(ctx, insertClickLog,
		arg.LinkID,
		arg.IpAddress,
		arg.Referer,
		arg.Country,
		arg.UserAgent,
		arg.ClickedAt,
	)
	var i ClickLog
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.IpAddress,
		&i.Referer,
		&i.Country,
		&i.UserAgent,
		&i.ClickedAt,
	)
	return i, err
}

const updateDailyCountries = `-- name: UpdateDailyCountries :exec
UPDATE daily_stats
SET countries = $3
WHERE link_id = $1 AND date = $2
`

type UpdateDailyCountriesParams struct {
	LinkID    int64       `json:"link_id"`
	Date      pgtype.Date `json:"date"`
	Countries []byte      `json:"countries"`
}

func (q *Queries) UpdateDailyCountries(ctx context.Context, arg UpdateDailyCountriesParams) error {
	_, err := q.db.Exec(ctx, updateDailyCountries, arg.LinkID, arg.Date, arg.Countries)
	return err
}

const updateDailyReferers = `-- name: UpdateDailyReferers :exec
UPDATE daily_stats
SET referers = $3
WHERE link_id = $1 AND date = $2
`

type UpdateDailyReferersParams struct {
	LinkID   int64       `json:"link_id"`
	Date     pgtype.Date `json:"date"`
	Referers []byte      `json:"referers"`
}

func (q *Queries) UpdateDailyReferers(ctx context.Context, arg UpdateDailyReferersParams) error {
	_, err := q.db.Exec(ctx, updateDailyReferers, arg.LinkID, arg.Date, arg.Referers)
	return err
}

const upsertDailyClicks = `-- name: UpsertDailyClicks :exec
INSERT INTO daily_stats (link_id, date, clicks, unique_visitors)
SELECT
    link_id,
    clicked_at::date AS date,
    COUNT(*) AS clicks,
    COUNT(DISTINCT md5(COALESCE(ip_address::text, '') || COALESCE(user_agent, ''))) AS unique_visitors
FROM click_logs
WHERE clicked_at >= $1 AND clicked_at < $2
GROUP BY link_id, clicked_at::date
ON CONFLICT (link_id, date)
DO UPDATE SET
    clicks = EXCLUDED.clicks,
    unique_visitors = EXCLUDED.unique_visitors
`

type UpsertDailyClicksParams struct {
	ClickedAt   pgtype.Timestamptz `json:"clicked_at"`
	ClickedAt_2 pgtype.Timestamptz `json:"clicked_at_2"`
}

func (q *Queries) UpsertDailyClicks(ctx context.Context, arg UpsertDailyClicksParams) error {
	_, err := q.db.Exec(ctx, upsertDailyClicks, arg.ClickedAt, arg.ClickedAt_2)
	return err
}
