// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url)
VALUES ($1)
RETURNING id, slug, original_url, total_clicks, created_at, is_deleted
`

func (q *Queries) CreateLink(ctx context.Context, originalUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, originalUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OriginalUrl,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getLinkByID = `-- name: GetLinkByID :one
SELECT id, slug, original_url, total_clicks, created_at, is_deleted
FROM links
WHERE id = $1
    AND is_deleted = FALSE
`

func (q *Queries) GetLinkByID(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByID, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OriginalUrl,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, slug, original_url, total_clicks, created_at, is_deleted
FROM links
WHERE slug = $1
    AND is_deleted = FALSE
`

func (q *Queries) GetLinkBySlug(ctx context.Context, slug pgtype.Text) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OriginalUrl,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const incrementTotalClicksSince = `-- name: IncrementTotalClicksSince :exec
UPDATE links
SET total_clicks = total_clicks + sub.cnt
FROM (
        SELECT link_id,
            COUNT(*) AS cnt
        FROM click_logs
        WHERE clicked_at > $1
        GROUP BY link_id
    ) AS sub
WHERE links.id = sub.link_id
`

func (q *Queries) IncrementTotalClicksSince(ctx context.Context, clickedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, incrementTotalClicksSince, clickedAt)
	return err
}

const softDeleteLink = `-- name: SoftDeleteLink :one
UPDATE links
SET is_deleted = TRUE
WHERE slug = $1
    AND is_deleted = FALSE
RETURNING id, slug, original_url, total_clicks, created_at, is_deleted
`

func (q *Queries) SoftDeleteLink(ctx context.Context, slug pgtype.Text) (Link, error) {
	row := q.db.QueryRow(ctx, softDeleteLink, slug)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OriginalUrl,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const updateLinkSlug = `-- name: UpdateLinkSlug :one
UPDATE links
SET slug = $1
WHERE id = $2
RETURNING id, slug, original_url, total_clicks, created_at, is_deleted
`

type UpdateLinkSlugParams struct {
	Slug pgtype.Text `json:"slug"`
	ID   int64       `json:"id"`
}

func (q *Queries) UpdateLinkSlug(ctx context.Context, arg UpdateLinkSlugParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLinkSlug, arg.Slug, arg.ID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.OriginalUrl,
		&i.TotalClicks,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}
